name: 'server-docker'

on:
  workflow_dispatch:
  push:
    paths:
      - 'apps/skylake-server/**'
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: setup node lts
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Install Packages
        run: pnpm i
      - name: Build
        run: cd apps/skylake-server && pnpm build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: apps/skylake-server
          file: apps/skylake-server/Dockerfile
          push: true
          tags: houzhenhong/skylake-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
